import type { Metadata } from 'next'

import './globals.css'
import Modal from '@/components/Modal'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#f5f6f8]'>{children}</body>
      <Modal/>
    </html>
  )
}
